# Generated by Django 3.0.3 on 2020-05-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscosas', '0002_auto_20200507_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentador',
            name='puntuacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alimentador',
            name='tipo',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='pagusuario',
            name='foto',
            field=models.TextField(default=''),
        ),
    ]
