# Generated by Django 3.0.3 on 2020-05-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscosas', '0003_auto_20200511_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='id_item',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='alimentador',
            name='elegido',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='alimentador',
            name='enlace',
            field=models.TextField(default=''),
        ),
    ]
