# Generated by Django 3.0.3 on 2020-05-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscosas', '0006_auto_20200513_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagusuario',
            name='foto',
            field=models.ImageField(upload_to='img_users'),
        ),
    ]
