# Generated by Django 3.0.3 on 2020-05-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscosas', '0007_auto_20200514_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimentador',
            name='puntuacion',
        ),
    ]
