# Generated by Django 3.0.3 on 2020-05-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscosas', '0008_remove_alimentador_puntuacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentador',
            name='id_canal',
            field=models.CharField(default='', max_length=64),
        ),
    ]
