# Generated by Django 3.0.3 on 2020-05-14 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscosas', '0009_alimentador_id_canal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id_item',
        ),
    ]
