# Generated by Django 3.0.3 on 2020-05-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscosas', '0012_comentario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='foto',
            field=models.ImageField(blank=True, upload_to='img_comens'),
        ),
    ]
