# Generated by Django 3.0.3 on 2020-05-16 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miscosas', '0013_auto_20200516_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentador',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
