# Generated by Django 3.0.3 on 2020-05-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscosas', '0014_alimentador_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alimentador',
            old_name='user',
            new_name='usuario',
        ),
    ]
