# Generated by Django 3.0.3 on 2020-05-16 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miscosas', '0015_auto_20200516_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentador',
            name='usuario',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
